// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// build_sfg_x
List build_sfg_x(List data_x, CharacterVector type, CharacterVector gtype);
RcppExport SEXP _sfgbuilder_build_sfg_x(SEXP data_xSEXP, SEXP typeSEXP, SEXP gtypeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type data_x(data_xSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type type(typeSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type gtype(gtypeSEXP);
    rcpp_result_gen = Rcpp::wrap(build_sfg_x(data_x, type, gtype));
    return rcpp_result_gen;
END_RCPP
}
