// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// build_polygons
List build_polygons(List data_xy);
RcppExport SEXP _sfgbuilder_build_polygons(SEXP data_xySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type data_xy(data_xySEXP);
    rcpp_result_gen = Rcpp::wrap(build_polygons(data_xy));
    return rcpp_result_gen;
END_RCPP
}
