# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Build sf
#'
#' @param data_xy list of xy data with no structure
#' @export
build_polygons <- function(data_xy) {
    .Call(`_sfgbuilder_build_polygons`, data_xy)
}

