# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

build_sfg_x <- function(data_x, type = "POLYGON", gtype = "XY") {
    .Call(`_sfgbuilder_build_sfg_x`, data_x, type, gtype)
}

